---
title: "Simple document"
author: Linshan Xie
date: 2024-10-24
output: github_document
---

```{r include = FALSE, message = FALSE, warning = FALSE}
library(ggplot2)
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
library(glmnet)

set.seed(1031)
```

## try Lasso!
import and clean the dataset "babyweight"
```{r}
bwt_df = 
  read_csv("data/birthweight.csv") |> 
  janitor::clean_names() |>
  mutate(
    babysex = 
        case_match(babysex,
            1 ~ "male",
            2 ~ "female"
        ),
    babysex = fct_infreq(babysex),
    frace = 
        case_match(frace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican", 
            8 ~ "other"),
    frace = fct_infreq(frace),
    mrace = 
        case_match(mrace,
            1 ~ "white",
            2 ~ "black", 
            3 ~ "asian", 
            4 ~ "puerto rican",
            8 ~ "other"),
    mrace = fct_infreq(mrace),
    malform = as.logical(malform)) |> 
  sample_n(200)
```

Construct inputs for `glmnet`
```{r}
x = model.matrix(bwt ~ ., data = bwt_df)[, -1]
y = bwt_df |>
  pull(bwt)
```

Fit lasso for several lambdas(列出一堆lambda，找到最合适model的lambda)
```{r}
lambda = 10^seq(-2, 2.75, by = 0.1)

lasso_fit = 
  glmnet(x = x, y = y, lambda = lambda)

lasso_cv = 
  cv.glmnet(x = x, y = y, lambda = lambda)

lambda_oprt = lasso_cv[["lambda.min"]]
```

usual lasso plot
```{r}
lasso_fit |>
  broom::tidy() |>
  filter(term != "(Intercept)") |>
  complete(term, lambda, fill = list(estimate = 0)) |>
  ggplot(aes(x = lambda, y = estimate, group = term, color = term)) +
  geom_vline(xintercept = lambda_oprt, color = "red") +
  geom_line()


lasso_cv |>
  broom::tidy() |>
  ggplot(aes(x = log(lambda, 10), y = estimate)) +
  geom_point()
```

```{r}
final_lasso_fit = 
  glmnet(x = x, y = y, lambda = lambda_oprt)

final_lasso_fit |>
  broom::tidy() |>
```



 